### ISSUE TITLE
Addon only loading some of the time

### ISSUE THREAD

**Issue by Nitroxko** [plsfixrito/AramBuddy#1]
This addon only loads some of the time for me and returns this error
```
Sandbox: Failed to load addon
System.TypeInitializationException: The type initializer for 'AramBuddy.Program' threw an exception. ---> SharpDX.SharpDXException: HRESULT: [0x8876086C], Module: [SharpDX.Direct3D9], ApiCode: [D3DERR_INVALIDCALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D9.D3DX9.CreateFont(Device deviceRef, Int32 height, Int32 width, Int32 weight, Int32 mipLevels, Bool italic, Int32 charSet, Int32 outputPrecision, Int32 quality, Int32 pitchAndFamily, String faceNameRef, Font fontOut)
   at SharpDX.Direct3D9.Font..ctor(Device device, Font font)
   at EloBuddy.SDK.Rendering.Text.ReplaceFont(Font font)
   at EloBuddy.SDK.Rendering.Text..ctor(String textValue, Font font)
   at AramBuddy.Program..cctor()
   --- End of inner exception stack trace ---
   at AramBuddy.Program.Main()
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(AssemblyName assemblyName, String[] args)
   at EloBuddy.Sandbox.SandboxDomain.LoadAddon(String path, String[] args)
```

**Comment by plsfixrito** [comment]
i'll check on it later today or this week

**Comment by plsfixrito** [comment]
fixed
